services:
  - type: web
    name: website-monitor-bot
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python setup_chromedriver.py
    startCommand: python main.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DISPLAY
        value: ":99"
    healthCheckPath: /health
