services:
  - type: web
    name: website-monitor-bot
    env: python  # Note: 'env' is deprecated; consider switching to 'runtime: python' for future-proofing
    plan: free
    # Remove the invalid 'pythonVersion' field
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python -m playwright install chromium
      python -m playwright install-deps
    startCommand: python main.py
    envVars:
      - key: PYTHON_VERSION  # Add this to specify Python 3.11.9
        value: 3.11.9
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
    healthCheckPath: /health